# permissions for end users to view monitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-viewer-role
rules:
- apiGroups:
  - datadog.github.com/skang0601/datadog-k8s-operator
  resources:
  - monitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datadog.github.com/skang0601/datadog-k8s-operator
  resources:
  - monitors/status
  verbs:
  - get
